#!/bin/bash

set -e

ROOT="$( dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd ) )"
cd $ROOT

pnpm exec esbuild --bundle src/run-cli.ts \
  --platform=node \
  --outfile=out/bundle.cjs \
  --log-level=warning \
  --format=cjs
